# Reference: https://github.com/i3/i3/blob/next/etc/config
#

after-startup-command = [
    'exec-and-forget borders active_color=0xff404344 width=8.0',
    'workspace 1',
]

exec-on-workspace-change = ['/bin/bash', '-c', '~/.config/aerospace/sticky-windows.sh $AEROSPACE_FOCUSED_WORKSPACE']

accordion-padding = 60

[exec]
inherit-env-vars = true
[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[mode.main.binding]

alt-h = 'focus left --boundaries all-monitors-outer-frame'
alt-j = 'focus down --boundaries all-monitors-outer-frame'
alt-k = 'focus up --boundaries all-monitors-outer-frame'
alt-l = 'focus right --boundaries all-monitors-outer-frame'

alt-shift-h = 'move left --boundaries all-monitors-outer-frame'
alt-shift-j = 'move down --boundaries all-monitors-outer-frame'
alt-shift-k = 'move up --boundaries all-monitors-outer-frame'
alt-shift-l = 'move right --boundaries all-monitors-outer-frame'


alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-c = 'reload-config'

alt-w = 'mode window'

alt-r = 'mode resize'
[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
r = ['reload-config', 'mode main']
enter = 'mode main'
esc = 'mode main'

[mode.window.binding]
# Arrangement
alt-w = ['layout tiling floating', 'mode main']
f = ['layout h_accordion tiles', 'mode main']
o = ['layout tiles horizontal vertical', 'mode main']


[[on-window-detected]]
check-further-callbacks = true
run = 'exec-and-forget ~/.config/aerospace/sticky-windows.sh'

# IDEs/Editors
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij-EAP'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = 'move-node-to-workspace 1'

# Terminals
[[on-window-detected]]
if.app-id = 'com.apple.Terminal'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = ['layout floating', 'move-node-to-workspace 2'] # ghostty has some tab weirdness with aerospace

# Web Browser
[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = 'move-node-to-workspace 3'

# Notes Apps
[[on-window-detected]]
if.app-name-regex-substring = 'Obsidian' # TODO: find the window id
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-name-regex-substring = 'Heptabase' # TODO: find the window id
run = 'move-node-to-workspace 7'

# Meeting Apps
[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = 'move-node-to-workspace 9'

# Tile these wherever they're called up
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout tiling']

# 1Password
# SSH Prompt (Must be ahead of com.1password.1password)
[[on-window-detected]]
if.window-title-regex-substring = '^1Password$'
run = ['layout floating']

# 1Password other windows
[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = ['layout tiling']

# Things I wish I could just make aerospace ignore entirely
[[on-window-detected]]
if.app-id = 'com.raycast.macos'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.calculator'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.sindresorhus.Dato' # TODO: Maybe this can be removed now
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.chabomakers.Antinote' # TODO: Antinote makes me cry, because it switches to the original workspace each time I focus the window
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.SecurityAgent'
run = 'layout floating'

# Fallback
[[on-window-detected]]
# run = ['move-node-to-monitor ^Built-in --focus-follows-window', 'layout tiling'] # this is more annoying than useful, as it turns out
run = ['move-node-to-workspace 10', 'layout floating']