# Reference: https://github.com/i3/i3/blob/next/etc/config
#
config-version = 2

after-startup-command = [
    'exec-and-forget borders active_color=0xff404344 width=8.0',
    'workspace 1',
]

exec-on-workspace-change = ['/bin/bash', '-c', '~/.config/aerospace/sticky-windows.sh $AEROSPACE_FOCUSED_WORKSPACE']

enable-normalization-flatten-containers = false

accordion-padding = 60

persistent-workspaces = [
    "meeting", # icon: person.crop.square.badge.video
    "comms", # icon: ellipsis.message.fill
    "notes", # icon: text.book.closed
    "primary", # icon: smallcircle.filled.circle.fill
    "secondary",  # icon: smallcircle.circle.fill
    "tertiary" # icon: circle.dotted.circle.fill
]

[exec]
inherit-env-vars = true
[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.left = 5
outer.bottom = 5
outer.top = 5
outer.right = 5

[workspace-to-monitor-force-assignment]
meeting = ['Elgato']

[mode.main.binding]

alt-h = 'focus left --boundaries all-monitors-outer-frame'
alt-j = 'focus down --boundaries all-monitors-outer-frame'
alt-k = 'focus up --boundaries all-monitors-outer-frame'
alt-l = 'focus right --boundaries all-monitors-outer-frame'

alt-shift-h = 'move left --boundaries all-monitors-outer-frame'
alt-shift-j = 'move down --boundaries all-monitors-outer-frame'
alt-shift-k = 'move up --boundaries all-monitors-outer-frame'
alt-shift-l = 'move right --boundaries all-monitors-outer-frame'

alt-shift-c = 'reload-config'
alt-f = 'fullscreen'

alt-w = 'mode window'

[mode.window.binding]
r = 'mode rearrange'
g = 'mode go'
m = 'mode move'
esc = 'mode main'

[mode.rearrange.binding] # LeaderKey: w > r "rearrange", activate mode only
h = 'focus left'
j = 'focus down'
k = 'focus up'
l = 'focus right'

shift-h = 'move left'
shift-j = 'move down'
shift-k = 'move up'
shift-l = 'move right'

alt-h = 'resize width -50'
alt-j = 'resize height +50'
alt-k = 'resize height -50'
alt-l = 'resize width +50'
t = 'layout tiles horizontal vertical'
a = 'layout accordion horizontal vertical'
c = 'layout tiling floating'

n = 'flatten-workspace-tree'

esc = 'mode main'

[mode.go.binding] # LeaderKey: w > g "go"
m = ['workspace meeting', 'mode main']
c = ['workspace comms', 'mode main']
n = ['workspace notes', 'mode main']
p = ['workspace primary', 'mode main']
s = ['workspace secondary', 'mode main']
t = ['workspace tertiary', 'mode main']
esc = 'mode main'

[mode.move.binding] # LeaderKey: w > m "move", icon: square.and.arrow.up.on.square
w = 'mode workspace'
d = 'mode display'
esc = 'mode main'

[mode.workspace.binding] # LeaderKey: w > m > w "workspace", icon: square.and.arrow.down.on.square.fill
m = ['move-node-to-workspace meeting --focus-follows-window', 'mode main']
c = ['move-node-to-workspace comms --focus-follows-window', 'mode main']
n = ['move-node-to-workspace notes --focus-follows-window', 'mode main']
p = ['move-node-to-workspace primary --focus-follows-window', 'mode main']
s = ['move-node-to-workspace secondary --focus-follows-window', 'mode main']
t = ['move-node-to-workspace tertiary --focus-follows-window', 'mode main']
esc = 'mode main'

[mode.display.binding] # LeaderKey: w > m > d "display", icon: desktopcomputer.and.macbook
e = ['move-workspace-to-monitor M32U', 'mode main'] # icon: tv
l = ['move-workspace-to-monitor built-in', 'mode main'] # icon: laptop
p = ['move-workspace-to-monitor Elgato', 'mode main'] # icon: tv.circle
esc = 'mode main'

[[on-window-detected]]
check-further-callbacks = true
run = 'exec-and-forget ~/.config/aerospace/sticky-windows.sh'

[[on-window-detected]]
if.window-title-regex-substring = "^Meet"
run = ['move-node-to-workspace meeting', 'layout tiling']

[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = ['move-node-to-workspace meeting', 'layout tiling']

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = ['move-node-to-workspace meeting', 'layout tiling']

# IDEs/Editors
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ['layout tiling', 'move-node-to-workspace primary']

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij-EAP'
run = ['layout tiling', 'move-node-to-workspace primary']

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = ['layout tiling', 'move-node-to-workspace primary']

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = ['layout floating', 'move-node-to-workspace primary'] # ghostty has some tab weirdness with aerospace

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = ['layout tiling', 'move-node-to-workspace primary']

# Comms Apps
[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = ['layout tiling', 'move-node-to-workspace comms']

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = ['layout tiling', 'move-node-to-workspace comms']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['layout tiling', 'move-node-to-workspace comms']

# Notes Apps
[[on-window-detected]]
if.app-id = 'md.obsidian'
run = ['layout tiling', 'move-node-to-workspace notes']

# Tile these wherever they're called up
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout tiling']

# 1Password
# SSH Prompt (Must be ahead of com.1password.1password)
[[on-window-detected]]
if.window-title-regex-substring = '^1Password$'
run = ['layout floating']

# 1Password other windows
[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = ['layout tiling']

# Leader Key
[[on-window-detected]]
if.app-id = 'com.brnbw.Leader-Key'
if.window-title-regex-substring = "^General$"
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.brnbw.Leader-Key'
if.window-title-regex-substring = "" # catch edit popups
run = 'layout floating'

# Things I wish I could just make aerospace ignore entirely
[[on-window-detected]]
if.app-id = 'com.raycast.macos'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.calculator'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.sindresorhus.Dato' # TODO: Maybe this can be removed now
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.chabomakers.Antinote' # TODO: Antinote makes me cry, because it switches to the original workspace each time I focus the window
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.SecurityAgent'
run = 'layout floating'

# Fallback
[[on-window-detected]]
# run = ['move-node-to-monitor ^Built-in --focus-follows-window', 'layout tiling'] # this is more annoying than useful, as it turns out
run = ['layout floating']