[drime]
type = drime
upload_cutoff = 10Mi

[dropbox]
type = dropbox

[filen]
type = filen
email = luke@lukebarton.co.uk

[cloud]
type = alias
remote = drime:

[keystone]
type = alias
remote = /Volumes/keystone